apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: default
      server: https://api-cotest-ppd-cluster-k8-kbgevp-1124127088.us-west-2.elb.amazonaws.com
    k8sVersion: v1.10.0
    path: default
  dev:
    destination:
      namespace: dev
      server: https://api-cotest-ppd-cluster-k8-kbgevp-1124127088.us-west-2.elb.amazonaws.com
    k8sVersion: v1.10.0
    path: dev
  prod:
    destination:
      namespace: prod
      server: https://api-cotest-ppd-cluster-k8-kbgevp-1124127088.us-west-2.elb.amazonaws.com
    k8sVersion: v1.10.0
    path: prod
kind: ksonnet.io/app
name: guestbook
version: 0.0.1
